<Project>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0" PrivateAssets="all"/>
<!--        <PackageReference Include="SonarAnalyzer.CSharp" Version="10.15.0.120848" PrivateAssets="all"/>-->
    </ItemGroup>
    
    <PropertyGroup>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="../CodeMetricsConfig.txt" />
    </ItemGroup>
</Project>
